### PR TITLE
#8 adventureworks - fix install script

### PR DESCRIPTION
**Pull request by jakubiszon**
this fixes the problem explained in issue #8 
I am not sure how to link this PR to the issue

### CODE REVIEW

**Comment by morenoh149** [comment]
thanks!

**Comment by morenoh149** [comment]
@jakubiszon btw does line 1233 need to change as well? just checking because that would fix issue https://github.com/morenoh149/postgresDBSamples/issues/11

```
\copy Sales.SpecialOfferProduct FROM './data/SpecialOfferProduct.csv' DELIMITER E'\t' CSV;
```

**Comment by jakubiszon** [comment]
Hmm, there is no reason for this file to sit in a different directory. I guess I have not spotted that one.

**Comment by jakubiszon** [comment]
Hmm, there is no reason for this file to sit in a different directory. I guess I have not spotted that one.
There also is a whole commented out section on line 666 which seems to have originated as a _solution_ to the same problem. It would be good to look into the `ProductReview.csv` data too. I will not promise I will find the time but who knows :)

**Comment by morenoh149** [comment]
I went ahead an unzipped the adventureworks database. Should be easier to maintain and review changes now.

**Pull request merged**
